{
    tokens = [
    RECORD_START='regexp:^S[1-9]'
    BYTE='regexp:([0-9A-F]{2})'
    EOL='regexp:\R'
    ]
  parserClass="com.github.derdan.srecord.SRecordParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="SRecord"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.derdan.srecord.psi"
  psiImplPackage="com.github.derdan.srecord.psi.impl"

  elementTypeHolderClass="com.github.derdan.srecord.psi.SRecordTypes"
  elementTypeClass="com.github.derdan.srecord.psi.SRecordElementType"
  tokenTypeClass="com.github.derdan.srecord.psi.SRecordTokenType"
}

srecordFile ::= record *

record ::= start count address data EOL?

start ::= RECORD_START
address ::= BYTE BYTE BYTE
count ::= BYTE   
data ::= BYTE*
